### ISSUE TITLE
Investigate the use of submodules to house some of the common functinoality here

### ISSUE THREAD

**Issue by shalinijoshi19** [openT2T/opent2t#33]
We have code here that houses shared utilities/libraries/classes referenced by *all* translators (eg Error class, logging library, Constants) to avoid adding more duplicate and redundant code to our repos. And this tracks investigating whether there is yet another way to do this outside of a shared repo and instead using submodules in node.js

**Comment by jasongin** [comment]
Git submodules are notoriously difficult to work with.

NPM package dependencies seem to be a natural fit here. Are you experiencing problems with that approach?

**Comment by shalinijoshi19** [comment]
Closing this out as this doesn't seem something we'd want to invest in esp after Jason's tip on submodules in general. I think the current dependency module approach is working well for shared library code.
