### ISSUE TITLE
Onboarding framework

### ISSUE THREAD

**Issue by tjaffri** [openT2T/opent2t#6]
This should include APIs for non-UI portions of onboarding, and some way to hook in (metadata-driven?) UI for onboarding. The same onboarding module should therefore become usable in different UIs (e.g. interactive console, headless scripts, client apps, websites, etc.)

Probably this should not include specific onboarding implementations, which belong in other repos. But existing ones would need to be updated to fit into this framework.

A simple test case would be to take the current Wink onboarding module in the onboarding repo and run it via the opent2t lib in different UIs, specifically an interactive console as well as a client app (e.g. the console app with cordova UX).

**Comment by arjun-msft** [comment]
This has been done.
